// <auto-generated />
using System;
using DAL.CATEGORIES;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.CATEGORIES.Migrations
{
    [DbContext(typeof(CategoriesDbContext))]
    [Migration("20210309125223_7")]
    partial class _7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BOL.BRANDS.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandID");

                    b.ToTable("Brand","brands");
                });

            modelBuilder.Entity("BOL.BRANDS.BrandCategory", b =>
                {
                    b.Property<int>("BrandCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandID")
                        .HasColumnType("int");

                    b.Property<int?>("FirstCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SecondCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("BrandCategoryID");

                    b.HasIndex("BrandID");

                    b.HasIndex("FirstCategoryID");

                    b.HasIndex("SecondCategoryID");

                    b.ToTable("BrandsCategory","brands");
                });

            modelBuilder.Entity("BOL.BRANDS.KeywordBrand", b =>
                {
                    b.Property<int>("BrandKeywordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BrandCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FirstCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecondCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("BrandKeywordID");

                    b.HasIndex("BrandCategoryID");

                    b.HasIndex("FirstCategoryID");

                    b.HasIndex("SecondCategoryID");

                    b.ToTable("KeywordBrand","brands");
                });

            modelBuilder.Entity("BOL.CATEGORIES.FifthCategory", b =>
                {
                    b.Property<int>("FifthCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<int?>("FirstCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FourthCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<int>("SearchCount")
                        .HasColumnType("int");

                    b.Property<string>("SearchKeywordName")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<int?>("SecondCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("ThirdCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.HasKey("FifthCategoryID");

                    b.HasIndex("FirstCategoryID");

                    b.HasIndex("FourthCategoryID");

                    b.HasIndex("SecondCategoryID");

                    b.HasIndex("ThirdCategoryID");

                    b.ToTable("FifthCategory","cat");
                });

            modelBuilder.Entity("BOL.CATEGORIES.FirstCategory", b =>
                {
                    b.Property<int>("FirstCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<string>("Keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<int>("SearchCount")
                        .HasColumnType("int");

                    b.Property<string>("SearchKeywordName")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.HasKey("FirstCategoryID");

                    b.ToTable("FirstCategory","cat");
                });

            modelBuilder.Entity("BOL.CATEGORIES.FourthCategory", b =>
                {
                    b.Property<int>("FourthCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<int?>("FirstCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<int>("SearchCount")
                        .HasColumnType("int");

                    b.Property<string>("SearchKeywordName")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<int?>("SecondCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("ThirdCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.HasKey("FourthCategoryID");

                    b.HasIndex("FirstCategoryID");

                    b.HasIndex("SecondCategoryID");

                    b.HasIndex("ThirdCategoryID");

                    b.ToTable("FourthCategory","cat");
                });

            modelBuilder.Entity("BOL.CATEGORIES.KeywordFifthCategory", b =>
                {
                    b.Property<int>("KeywordFifthCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<int?>("FifthCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FirstCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FourthCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("SearchCount")
                        .HasColumnType("int");

                    b.Property<int?>("SecondCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ThirdCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("KeywordFifthCategoryID");

                    b.HasIndex("FifthCategoryID");

                    b.HasIndex("FirstCategoryID");

                    b.HasIndex("FourthCategoryID");

                    b.HasIndex("SecondCategoryID");

                    b.HasIndex("ThirdCategoryID");

                    b.ToTable("KeywordFifthCategory","cat");
                });

            modelBuilder.Entity("BOL.CATEGORIES.KeywordFirstCategory", b =>
                {
                    b.Property<int>("KeywordFirstCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<int?>("FirstCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("SearchCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("KeywordFirstCategoryID");

                    b.HasIndex("FirstCategoryID");

                    b.ToTable("KeywordFirstCategory","cat");
                });

            modelBuilder.Entity("BOL.CATEGORIES.KeywordFourthCategory", b =>
                {
                    b.Property<int>("KeywordFourthCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<int?>("FifthCategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("FirstCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FourthCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("SearchCount")
                        .HasColumnType("int");

                    b.Property<int?>("SecondCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ThirdCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("KeywordFourthCategoryID");

                    b.HasIndex("FifthCategoryID");

                    b.HasIndex("FirstCategoryID");

                    b.HasIndex("FourthCategoryID");

                    b.HasIndex("SecondCategoryID");

                    b.HasIndex("ThirdCategoryID");

                    b.ToTable("KeywordFourthCategory","cat");
                });

            modelBuilder.Entity("BOL.CATEGORIES.KeywordSecondCategory", b =>
                {
                    b.Property<int>("KeywordSecondCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<int?>("FifthCategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("FirstCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FourthCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("SearchCount")
                        .HasColumnType("int");

                    b.Property<int?>("SecondCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ThirdCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("KeywordSecondCategoryID");

                    b.HasIndex("FifthCategoryID");

                    b.HasIndex("FirstCategoryID");

                    b.HasIndex("FourthCategoryID");

                    b.HasIndex("SecondCategoryID");

                    b.HasIndex("ThirdCategoryID");

                    b.ToTable("KeywordSecondCategory","cat");
                });

            modelBuilder.Entity("BOL.CATEGORIES.KeywordSixthCategory", b =>
                {
                    b.Property<int>("KeywordSixthCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<int?>("FifthCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FirstCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FourthCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("SearchCount")
                        .HasColumnType("int");

                    b.Property<int?>("SecondCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SixthCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ThirdCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("KeywordSixthCategoryID");

                    b.HasIndex("FifthCategoryID");

                    b.HasIndex("FirstCategoryID");

                    b.HasIndex("FourthCategoryID");

                    b.HasIndex("SecondCategoryID");

                    b.HasIndex("SixthCategoryID");

                    b.HasIndex("ThirdCategoryID");

                    b.ToTable("KeywordSixthCategory","cat");
                });

            modelBuilder.Entity("BOL.CATEGORIES.KeywordThirdCategory", b =>
                {
                    b.Property<int>("KeywordThirdCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<int?>("FifthCategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("FirstCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FourthCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("SearchCount")
                        .HasColumnType("int");

                    b.Property<int?>("SecondCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ThirdCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("KeywordThirdCategoryID");

                    b.HasIndex("FifthCategoryID");

                    b.HasIndex("FirstCategoryID");

                    b.HasIndex("FourthCategoryID");

                    b.HasIndex("SecondCategoryID");

                    b.HasIndex("ThirdCategoryID");

                    b.ToTable("KeywordThirdCategory","cat");
                });

            modelBuilder.Entity("BOL.CATEGORIES.ListingTitle", b =>
                {
                    b.Property<int>("TitleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FirstCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecondCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TitleID");

                    b.HasIndex("FirstCategoryID");

                    b.HasIndex("SecondCategoryID");

                    b.ToTable("ListingTitle","cat");
                });

            modelBuilder.Entity("BOL.CATEGORIES.NewSearchTerm", b =>
                {
                    b.Property<int>("NewSearchTermID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("SearchDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewSearchTermID");

                    b.ToTable("NewSearchTerm","cat");
                });

            modelBuilder.Entity("BOL.CATEGORIES.Pages", b =>
                {
                    b.Property<int>("PageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageID");

                    b.ToTable("Pages","cms");
                });

            modelBuilder.Entity("BOL.CATEGORIES.SecondCategory", b =>
                {
                    b.Property<int>("SecondCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<int?>("FirstCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<int>("SearchCount")
                        .HasColumnType("int");

                    b.Property<string>("SearchKeywordName")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.HasKey("SecondCategoryID");

                    b.HasIndex("FirstCategoryID");

                    b.ToTable("SecondCategory","cat");
                });

            modelBuilder.Entity("BOL.CATEGORIES.SixthCategory", b =>
                {
                    b.Property<int>("SixthCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<int?>("FifthCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FirstCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FourthCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<int>("SearchCount")
                        .HasColumnType("int");

                    b.Property<string>("SearchKeywordName")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<int?>("SecondCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("ThirdCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.HasKey("SixthCategoryID");

                    b.HasIndex("FifthCategoryID");

                    b.HasIndex("FirstCategoryID");

                    b.HasIndex("FourthCategoryID");

                    b.HasIndex("SecondCategoryID");

                    b.HasIndex("ThirdCategoryID");

                    b.ToTable("SixthCategory","cat");
                });

            modelBuilder.Entity("BOL.CATEGORIES.ThirdCategory", b =>
                {
                    b.Property<int>("ThirdCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(153)")
                        .HasMaxLength(153);

                    b.Property<int?>("FirstCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<int>("SearchCount")
                        .HasColumnType("int");

                    b.Property<string>("SearchKeywordName")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<int?>("SecondCategoryID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.HasKey("ThirdCategoryID");

                    b.HasIndex("FirstCategoryID");

                    b.HasIndex("SecondCategoryID");

                    b.ToTable("ThirdCategory","cat");
                });

            modelBuilder.Entity("BOL.BRANDS.BrandCategory", b =>
                {
                    b.HasOne("BOL.BRANDS.Brand", "Brand")
                        .WithMany("BrandCategory")
                        .HasForeignKey("BrandID");

                    b.HasOne("BOL.CATEGORIES.FirstCategory", "FirstCategory")
                        .WithMany("BrandsCategory")
                        .HasForeignKey("FirstCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.SecondCategory", "SecondCategory")
                        .WithMany("BrandsCategory")
                        .HasForeignKey("SecondCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOL.BRANDS.KeywordBrand", b =>
                {
                    b.HasOne("BOL.BRANDS.BrandCategory", "BrandCategory")
                        .WithMany("KeywordBrand")
                        .HasForeignKey("BrandCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.FirstCategory", "FirstCategory")
                        .WithMany("KeywordBrand")
                        .HasForeignKey("FirstCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.SecondCategory", "SecondCategory")
                        .WithMany("KeywordBrand")
                        .HasForeignKey("SecondCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOL.CATEGORIES.FifthCategory", b =>
                {
                    b.HasOne("BOL.CATEGORIES.FirstCategory", "FirstCategory")
                        .WithMany("FifthCategory")
                        .HasForeignKey("FirstCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.FourthCategory", "FourthCategory")
                        .WithMany("FifthCategory")
                        .HasForeignKey("FourthCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.SecondCategory", "SecondCategory")
                        .WithMany("FifthCategory")
                        .HasForeignKey("SecondCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.ThirdCategory", "ThirdCategory")
                        .WithMany("FifthCategory")
                        .HasForeignKey("ThirdCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOL.CATEGORIES.FourthCategory", b =>
                {
                    b.HasOne("BOL.CATEGORIES.FirstCategory", "FirstCategory")
                        .WithMany("FourthCategory")
                        .HasForeignKey("FirstCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.SecondCategory", "SecondCategory")
                        .WithMany("FourthCategory")
                        .HasForeignKey("SecondCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.ThirdCategory", "ThirdCategory")
                        .WithMany("FourthCategory")
                        .HasForeignKey("ThirdCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOL.CATEGORIES.KeywordFifthCategory", b =>
                {
                    b.HasOne("BOL.CATEGORIES.FifthCategory", "FifthCategory")
                        .WithMany("KeywordFifthCategory")
                        .HasForeignKey("FifthCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.FirstCategory", "FirstCategory")
                        .WithMany("KeywordFifthCategory")
                        .HasForeignKey("FirstCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.FourthCategory", "FourthCategory")
                        .WithMany("KeywordFifthCategory")
                        .HasForeignKey("FourthCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.SecondCategory", "SecondCategory")
                        .WithMany("KeywordFifthCategory")
                        .HasForeignKey("SecondCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.ThirdCategory", "ThirdCategory")
                        .WithMany("KeywordFifthCategory")
                        .HasForeignKey("ThirdCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOL.CATEGORIES.KeywordFirstCategory", b =>
                {
                    b.HasOne("BOL.CATEGORIES.FirstCategory", "FirstCategory")
                        .WithMany("KeywordFirstCategory")
                        .HasForeignKey("FirstCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOL.CATEGORIES.KeywordFourthCategory", b =>
                {
                    b.HasOne("BOL.CATEGORIES.FifthCategory", null)
                        .WithMany("KeywordFourthCategory")
                        .HasForeignKey("FifthCategoryID");

                    b.HasOne("BOL.CATEGORIES.FirstCategory", "FirstCategory")
                        .WithMany("KeywordFourthCategory")
                        .HasForeignKey("FirstCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.FourthCategory", "FourthCategory")
                        .WithMany("KeywordFourthCategory")
                        .HasForeignKey("FourthCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.SecondCategory", "SecondCategory")
                        .WithMany("KeywordFourthCategory")
                        .HasForeignKey("SecondCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.ThirdCategory", "ThirdCategory")
                        .WithMany("KeywordFourthCategory")
                        .HasForeignKey("ThirdCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOL.CATEGORIES.KeywordSecondCategory", b =>
                {
                    b.HasOne("BOL.CATEGORIES.FifthCategory", null)
                        .WithMany("KeywordSecondCategory")
                        .HasForeignKey("FifthCategoryID");

                    b.HasOne("BOL.CATEGORIES.FirstCategory", "FirstCategory")
                        .WithMany("KeywordSecondCategory")
                        .HasForeignKey("FirstCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.FourthCategory", null)
                        .WithMany("KeywordSecondCategory")
                        .HasForeignKey("FourthCategoryID");

                    b.HasOne("BOL.CATEGORIES.SecondCategory", "SecondCategory")
                        .WithMany("KeywordSecondCategory")
                        .HasForeignKey("SecondCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.ThirdCategory", null)
                        .WithMany("KeywordSecondCategory")
                        .HasForeignKey("ThirdCategoryID");
                });

            modelBuilder.Entity("BOL.CATEGORIES.KeywordSixthCategory", b =>
                {
                    b.HasOne("BOL.CATEGORIES.FifthCategory", "FifthCategory")
                        .WithMany("KeywordSixthCategory")
                        .HasForeignKey("FifthCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.FirstCategory", "FirstCategory")
                        .WithMany("KeywordSixthCategory")
                        .HasForeignKey("FirstCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.FourthCategory", "FourthCategory")
                        .WithMany("KeywordSixthCategory")
                        .HasForeignKey("FourthCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.SecondCategory", "SecondCategory")
                        .WithMany("KeywordSixthCategory")
                        .HasForeignKey("SecondCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.SixthCategory", "SixthCategory")
                        .WithMany("KeywordSixthCategory")
                        .HasForeignKey("SixthCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.ThirdCategory", "ThirdCategory")
                        .WithMany("KeywordSixthCategory")
                        .HasForeignKey("ThirdCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOL.CATEGORIES.KeywordThirdCategory", b =>
                {
                    b.HasOne("BOL.CATEGORIES.FifthCategory", null)
                        .WithMany("KeywordThirdCategory")
                        .HasForeignKey("FifthCategoryID");

                    b.HasOne("BOL.CATEGORIES.FirstCategory", "FirstCategory")
                        .WithMany("KeywordThirdCategory")
                        .HasForeignKey("FirstCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.FourthCategory", null)
                        .WithMany("KeywordThirdCategory")
                        .HasForeignKey("FourthCategoryID");

                    b.HasOne("BOL.CATEGORIES.SecondCategory", "SecondCategory")
                        .WithMany("KeywordThirdCategory")
                        .HasForeignKey("SecondCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.ThirdCategory", "ThirdCategory")
                        .WithMany("KeywordThirdCategory")
                        .HasForeignKey("ThirdCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOL.CATEGORIES.ListingTitle", b =>
                {
                    b.HasOne("BOL.CATEGORIES.FirstCategory", "FirstCategory")
                        .WithMany("ListingTitle")
                        .HasForeignKey("FirstCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.SecondCategory", "SecondCategory")
                        .WithMany("ListingTitle")
                        .HasForeignKey("SecondCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOL.CATEGORIES.SecondCategory", b =>
                {
                    b.HasOne("BOL.CATEGORIES.FirstCategory", "FirstCategory")
                        .WithMany("SecondCategory")
                        .HasForeignKey("FirstCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOL.CATEGORIES.SixthCategory", b =>
                {
                    b.HasOne("BOL.CATEGORIES.FifthCategory", "FifthCategory")
                        .WithMany("SixthCategory")
                        .HasForeignKey("FifthCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.FirstCategory", "FirstCategory")
                        .WithMany("SixthCategory")
                        .HasForeignKey("FirstCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.FourthCategory", "FourthCategory")
                        .WithMany("SixthCategory")
                        .HasForeignKey("FourthCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.SecondCategory", "SecondCategory")
                        .WithMany("SixthCategory")
                        .HasForeignKey("SecondCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.ThirdCategory", "ThirdCategory")
                        .WithMany("SixthCategory")
                        .HasForeignKey("ThirdCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BOL.CATEGORIES.ThirdCategory", b =>
                {
                    b.HasOne("BOL.CATEGORIES.FirstCategory", "FirstCategory")
                        .WithMany("ThirdCategory")
                        .HasForeignKey("FirstCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOL.CATEGORIES.SecondCategory", "SecondCategory")
                        .WithMany("ThirdCategory")
                        .HasForeignKey("SecondCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
